server:
  port: 8080

tigrisdb:
  db:
    name: "tigrisdb-starter-java"
  server:
    url: "localhost:8081"
  network:
    usePlainText: true
  authorization:
    token: "some-token"

springdoc:
  swagger-ui:
    path: "/swagger.html"
    operationsSorter: "method"