server:
  port: 8080

tigris:
  db:
    name: "tigris_starter_java"
  server:
    url: "localhost:8081"
  network:
    usePlainText: true

springdoc:
  swagger-ui:
    path: "/swagger.html"
    operationsSorter: "method"