server:
  port: 8080

## Tigris cloud configuration
tigris:
  project:
    name: "tigris_starter_java"
  db:
    collectionClasses: com.tigrisdata.starter.collections.Order,com.tigrisdata.starter.collections.Product,com.tigrisdata.starter.collections.User
  server:
    url: "api.preview.tigrisdata.cloud"
  network:
    usePlainText: false
  auth:
    clientId: "<your-app_key-client-id>"
    clientSecret: "<your-app_key-client-secret>"
  sync-client:
    enabled: true
    initializer:
      enabled: true

springdoc:
  swagger-ui:
    path: "/swagger.html"
    operationsSorter: "method"

## this is to avoid exposing tigris secrets on actuator endpoints
endpoints:
  env:
    keys-to-sanitize: tigris.auth.clientId,tigris.auth.clientSecret
  configprops:
    keys-to-sanitize: tigris.auth.clientId,tigris.auth.clientSecret
